image: Visual Studio 2022

cache:
  - '%LOCALAPPDATA%\pip\cache -> requirements.txt'
install:
  - 'C:\Python311-x64\python.exe -m virtualenv venv'
  - '.\venv\Scripts\pip install --upgrade -r requirements.txt pytest'
build_script:
  - '.\venv\Scripts\python setup.py bdist_wheel'
  - 'move /y dist\*.whl .'
  - sha1sum *.whl
test_script:
  - '.\venv\Scripts\python -m pytest'
artifacts:
  - path: '*.whl'
    name: whl
deploy:
  provider: S3
  access_key_id: AKIAJCSEQOUWIU2HK3SQ
  secret_access_key:
    secure: gKHiok/Emkvb298mPcxWXTn2ttSFnRTEmsaTYex3qZlqHSRVptKjvD2bVeA4XJ7a
  bucket: pypi.metamorphsoftware.com
  region: us-east-1
  artifact: whl
  folder: run-mdao
  on:
    appveyor_repo_tag: true
